import type { Metadata } from "next";
import { Provider } from 'react-redux';

import "./globals.css";
import "react-phone-input-2/lib/style.css";
import { ThemeProvider } from "@/components/ui/theme-provider";
import { ConvexClientProvider } from "./provider/ConvexClientProvider";
import { AuthProvider } from "./provider/AuthContext";
import store from '@/store';


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <body>
        {/* <Provider store={store}> */}
          <AuthProvider>
            <ConvexClientProvider>
              <ThemeProvider
                attribute="class"
                defaultTheme="dark"
                enableSystem
                disableTransitionOnChange
              >
                {children}
              </ThemeProvider>
            </ConvexClientProvider>
          </AuthProvider>
        {/* </Provider> */}
      </body>
    </html>
  );
}
