import Link from "next/link"
import ReviewCarousel from "../carousel/reviewCarousel"

export interface RecentReviewsProps {
    rate: number,
    amount: number,
    desc: string,
    examples: {
        name: string,
        date: string,
        feed: string,
        url: string
    }[]
}

const RecentReviews = (props: RecentReviewsProps) => {
    return (
        <div className="rounded-[20px] bg-[#201E23] overflow-hidden mt-[5px] p-[24px]">
            <h1 className="text-[20px] font-bold">Recent reviews</h1>
            <div className="flex items-center justify-start gap-[5px] text-[rgb(191, 186, 196)] mt-[5px]">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" viewBox="0 0 256 256"><path d="M234.29,114.85l-45,38.83L203,211.75a16.4,16.4,0,0,1-24.5,17.82L128,198.49,77.47,229.57A16.4,16.4,0,0,1,53,211.75l13.76-58.07-45-38.83A16.46,16.46,0,0,1,31.08,86l59-4.76,22.76-55.08a16.36,16.36,0,0,1,30.27,0l22.75,55.08,59,4.76a16.46,16.46,0,0,1,9.37,28.86Z"></path></svg>
                <span className="underline">{props.rate}({props.amount})</span>
            </div>
            <p className="mt-[20px] font-[500] text-[17px]">{props.desc}</p>

            <div className="flex items-center justify-start gap-[5px] text-[#817a8a] mt-[20px]">
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="#C7BDFF" aria-hidden="true" data-slot="icon" weight="solid" stroke="#C7BDFF" width="16" height="16"><path fill-rule="evenodd" d="M9 4.5a.75.75 0 0 1 .721.544l.813 2.846a3.75 3.75 0 0 0 2.576 2.576l2.846.813a.75.75 0 0 1 0 1.442l-2.846.813a3.75 3.75 0 0 0-2.576 2.576l-.813 2.846a.75.75 0 0 1-1.442 0l-.813-2.846a3.75 3.75 0 0 0-2.576-2.576l-2.846-.813a.75.75 0 0 1 0-1.442l2.846-.813A3.75 3.75 0 0 0 7.466 7.89l.813-2.846A.75.75 0 0 1 9 4.5ZM18 1.5a.75.75 0 0 1 .728.568l.258 1.036c.236.94.97 1.674 1.91 1.91l1.036.258a.75.75 0 0 1 0 1.456l-1.036.258c-.94.236-1.674.97-1.91 1.91l-.258 1.036a.75.75 0 0 1-1.456 0l-.258-1.036a2.625 2.625 0 0 0-1.91-1.91l-1.036-.258a.75.75 0 0 1 0-1.456l1.036-.258a2.625 2.625 0 0 0 1.91-1.91l.258-1.036A.75.75 0 0 1 18 1.5ZM16.5 15a.75.75 0 0 1 .712.513l.394 1.183c.15.447.5.799.948.948l1.183.395a.75.75 0 0 1 0 1.422l-1.183.395c-.447.15-.799.5-.948.948l-.395 1.183a.75.75 0 0 1-1.422 0l-.395-1.183a1.5 1.5 0 0 0-.948-.948l-1.183-.395a.75.75 0 0 1 0-1.422l1.183-.395c.447-.15.799-.5.948-.948l.395-1.183A.75.75 0 0 1 16.5 15Z" clip-rule="evenodd"></path></svg>
                <p className="#817a8a text-[14px]">
                    Review summary generated by Cameo AI
                </p>
            </div>
            <ReviewCarousel data={props.examples} />

            <Link href={"#"} className="block w-full rounded-full p-[12px] border border-[#F2F1F399] text-center font-bold mt-[20px]">Show all {props.amount} reviews</Link>
        </div>
    )
}

export default RecentReviews